services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-alurafood
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka-alurafood
    ports:
      - "8081:8761"